

server:
  port: 9006
  servlet:
    context-path: /qr
  undertow:
    io-threads: 1
    worker-threads: 1
    buffer-size: 8196
logging:
  config: classpath:log4j2.xml
spring:
  profiles:
    active: dev

