server:
  port: 8088

rabbit:
  host: 192.168.100.101
  port: 5672
  userName: test
  password: test
  exchange:
    directExchange: direct
    topicExchange: topic
  queue: test
  routingKey: test

spring:
   redis:
       host: 192.168.100.101
       port: 5379
       password: test
       pool:
          maxActive: 10
          minIdle: 2
          maxWait: 30000
geo:
   hashkey: postion:geo

redis:
    nodes:
       - host: 192.168.100.101
         port: 6379
         password: test
