spring:
  kafka:
    producer:
      topic: test
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
  task:
    scheduling:
      pool:
        size: 8
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: producer-