spring:
  kafka:
    producer:
      topic: test
      key-serializer: com.tiger.kafka.serializer.KryoKafkaSerializer
      value-serializer: com.tiger.kafka.serializer.KryoKafkaSerializer
      acks: 1
      compression-type: snappy
      properties:
        key-type: java.lang.Long
        value-type: com.tiger.kafka.entity.User
  task:
    scheduling:
      pool:
        size: 8
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: producer-