spring:
  profiles:
    active: producer
  kafka:
    bootstrap-servers: 192.168.100.3:9092
#    properties:
#      sasl:
#        mechanism: SCRAM-SHA-256
#        jaas:
#          config: org.apache.kafka.common.security.scram.ScramLoginModule  required username="test" password="test";
#      security:
#        protocol: SASL_PLAINTEXT
logging:
  config: classpath:log4j2.xml

