consumer:
  topics: test
  concurrency: 4
spring:
  kafka:
    consumer:
      group-id: test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000
      auto-offset-reset: earliest
