spring:
  kafka:
    producer:
      topic: t1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      compression-type: none
      properties:
        key-type: java.lang.Long
        value-type: com.tiger.kafka.entity.User
  task:
    scheduling:
      pool:
        size: 8
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: producer-